common: &common_settings
    application_name: "publicardo"
    debug: true
    log_level:  "DEBUG"
    log_filename:   "autonotifier.log"
    folders:
        layout: "local"
        source_folder: "source"
        destination_folder: "destination"
    resize:
        wide_side_length: 1200
    exif:
        preserve_author: true
    watermark:
        font: "Tahoma.ttf"
        text: "© Alexander Lockshyn | travelfreak.ru"
        color: "#efefef"
        background_color: "#000000"
        font_size: 24
        margin: 10
        text_opacity: 1
        background_opacity: 0.6

development:
    <<: *common_settings

test:
    <<: *common_settings

production:
    <<: *common_settings

staging:
    <<: *common_settings
